# Generated by Django 4.1.7 on 2023-04-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
