# Generated by Django 4.1.7 on 2023-04-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('JsonData', models.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='temporary',
            index=models.Index(fields=['StartDate'], name='blog_tempor_StartDa_ae39ea_idx'),
        ),
        migrations.AddIndex(
            model_name='temporary',
            index=models.Index(fields=['EndDate'], name='blog_tempor_EndDate_de3122_idx'),
        ),
    ]
