# Generated by Django 4.1.7 on 2023-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_temporary_temporary_blog_tempor_startda_ae39ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
